name: ssh-key-manager
base: core24
version: '0.1.0'
summary: TUI/CLI application for managing SSH keys
description: |
  SSH Key Manager (skm) is a user-friendly TUI/CLI application for managing 
  SSH keys on Linux, macOS, and Windows.
  
  Features:
  - Interactive TUI for managing SSH keys
  - Generate new SSH keys (ED25519, RSA)
  - Export/Import encrypted backups
  - CLI mode for automation and cron jobs
  - Cross-platform support

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    build-for: amd64
  - build-on: arm64
    build-for: arm64

apps:
  skm:
    command: bin/skm
    plugs:
      - home
      - ssh-keys
    environment:
      # Ensure we can access user's SSH directory
      SSH_DIR: $HOME/.ssh

parts:
  ssh-key-manager:
    plugin: rust
    source: .
    rust-channel: stable
    rust-features: []
    build-packages:
      - pkg-config
      - libssl-dev
    stage-packages:
      - libssl3
    override-build: |
      # Build the release binary
      cargo build --release
      # Install binary to snap bin directory
      install -D -m755 target/release/skm $SNAPCRAFT_PART_INSTALL/bin/skm

plugs:
  ssh-keys:
    interface: personal-files
    read:
      - $HOME/.ssh
    write:
      - $HOME/.ssh
